version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Screenspace
    ports:
      - 3677:3306

  app:
    image: cowanr/cowanr
    ports:
       - 8090:8080
    depends_on:
       - docker-mysql